/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrittonTreeRouteImport } from './routes/britton-tree'
import { Route as IndexRouteImport } from './routes/index'

const BrittonTreeRoute = BrittonTreeRouteImport.update({
  id: '/britton-tree',
  path: '/britton-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/britton-tree': typeof BrittonTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/britton-tree': typeof BrittonTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/britton-tree': typeof BrittonTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/britton-tree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/britton-tree'
  id: '__root__' | '/' | '/britton-tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrittonTreeRoute: typeof BrittonTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/britton-tree': {
      id: '/britton-tree'
      path: '/britton-tree'
      fullPath: '/britton-tree'
      preLoaderRoute: typeof BrittonTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrittonTreeRoute: BrittonTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
